apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
data:
  LOG_LEVEL: "info"
  SERVER_PORT: "8081"
  WELCOME_MESSAGE: "Welcome to the configured server app"
  LOG_FILE_PATH: "/app/logs/app.log"