apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istio-envoy
  namespace: monitoring
  labels:
    release: kube-prom-stack
spec:
  selector:
    matchLabels:
      app: server
  namespaceSelector:
    any: true
  endpoints:
    - port: http-envoy-prom
      path: /stats/prometheus
      interval: 15s
    - port: http
      path: /metrics
      interval: 15s